--
-- Name:        cmake/cmake_workspace.lua
-- Purpose:     Generate a cmake workspace.
-- Author:      Ryan Pusztai
-- Modified by: Andrea Zanellato
--              Manu Evans
-- Created:     2013/05/06
-- Copyright:   (c) 2008-2015 Jason Perkins and the Premake project
--

	local p = premake
	local project = p.project
	local workspace = p.workspace
	local tree = p.tree
	local cmake = p.modules.cmake

	cmake.workspace = {}
	local m = cmake.workspace

--
-- Generate root CMakeLists.txt at workspace location
--
	function m.generateRoot(wks)
		p.utf8()

		p.w('cmake_minimum_required(VERSION 3.16)')
		p.w('project(%s VERSION 1.0.0 LANGUAGES C CXX)', wks.name)
		p.w('')
		p.w('set(CMAKE_CXX_STANDARD 23)')
		p.w('set(CMAKE_CXX_STANDARD_REQUIRED ON)')
		p.w('set(CMAKE_EXPORT_COMPILE_COMMANDS ON)')
		p.w('')
		p.w('# Build type defaults')
		p.w('if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)')
		p.w('    set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Build type" FORCE)')
		p.w('    set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "Debug" "Release" "RelWithDebInfo" "MinSizeRel")')
		p.w('endif()')
		p.w('')
		p.w('# Output directories')
		p.w('set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)')
		p.w('set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)')
		p.w('set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)')
		p.w('')
		p.w('# Add cmake-bins subdirectory with all project definitions')
		p.w('add_subdirectory(cmake-bins)')
	end

--
-- Generate cmake-bins/CMakeLists.txt that includes all projects
--
	function m.generate(wks)
		p.utf8()

		p.w('# Project definitions for %s', wks.name)
		p.w('# Generated by premake5 cmake')
		p.w('')

		-- count the number of platforms
		local platformsPresent = {}
		local numPlatforms = 0

		for cfg in workspace.eachconfig(wks) do
			local platform = cfg.platform
			if platform and not platformsPresent[platform] then
				numPlatforms = numPlatforms + 1
				platformsPresent[platform] = true
			end
		end

		if numPlatforms >= 2 then
			cmake.workspace.multiplePlatforms = true
		end

		-- Include all project cmake files
		local tr = workspace.grouptree(wks)
		tree.traverse(tr, {
			onleaf = function(n)
				local prj = n.project
				p.w('include(${CMAKE_CURRENT_SOURCE_DIR}/%s.cmake)', prj.name)
			end,

			onbranchenter = function(n)
				-- Could add comments for groups
				-- p.w('# Group: %s', n.name)
			end,

			onbranchexit = function(n)
			end,
		})
	end
